### ISSUE TITLE
Version List Broken

### ISSUE THREAD

**Issue by zicklag** [spicylobstergames/SpicyLauncher#10]
The version list updated automatically by CI now contains a redirect instead of a list of versions:

```json
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/379429942/releases",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}
```

This actually causes the launcher to crash at startup.

It might have been the fishfolk rename. Looks like we probably just need to update the secret for CI.

**Comment by orhun** [comment]
Secret is updated for CI. Thanks!
