### ISSUE TITLE
Launch Options

### ISSUE THREAD

**Issue by zicklag** [spicylobstergames/SpicyLauncher#22]
When launching Jumpy, users may want to enable the hot-reload feature, which is disabled by default and enabled with a commandline flag. It might be good to have some way to configure this in the launcher.

I'm not sure if this would be best accomplished by having game-specific launch config that could be modified in the launcher, or if maybe we should have a global set of configuration options, in like a settings menu that would allow you to set flags across all of the games.

**Comment by erlend-sh** [comment]
Why do we disable it by default?

**Comment by zicklag** [comment]
Because you don't really need a filesystem watcher enabled by default unless you're modding, and if you were modding, it initially seemed like not a big deal to enable it since you're already doing "abnormal" stuff.

Enabling it technically uses more system resources ( though it might not _actually_ be a big deal, I don't know ) so it seems like we might not want to enable it without the user choosing to.

Now that I say that, though, I'm just realizing we could just add a setting to the Jumpy settings menu, which would be better.

I'll close this issue and open one for a hot-reload setting in Jumpy.
