### ISSUE TITLE
follow XDG Base Directory Specification on Linux

### ISSUE THREAD

**Issue by etam** [spicylobstergames/SpicyLauncher#24]
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

This might be helpful: https://crates.io/crates/directories

**Comment by orhun** [comment]
I'm not sure what is requested to be done here. Do you mean adding a desktop file? Change the data/config location? Can you be more specific please?

**Comment by etam** [comment]
Change the data/config location. Instead of
```rust
pub const DATA_DIR: &str = ".spicylauncher";
```
Use [directories::ProjectDirs::data_dir](https://docs.rs/directories/5.0.1/directories/struct.ProjectDirs.html#method.data_dir)

**Comment by orhun** [comment]
Done in d33d77fb47f3de4c962cd80c54d61600dbb98982
This is good because Tauri also uses `~/.local/share/spicy-launcher` which means now we have a central place for the launcher assets.
